### ISSUE TITLE
Верхнее меню на мобильнике

### ISSUE THREAD

**Issue by politsin** [synapse-studio/adaptive#5]
Пример тут
http://465-p-kalkulator.n2.s1dev.ru/

Если посмотреть на мобильном - ссылки должны быть вертикально и по центру + хорошо бы сделать рабочим 2й уровено меню 
http://465-p-kalkulator.n2.s1dev.ru/sites/default/files/menu.png

Можно править прямо на этом сайте, там последняя версия темы.
https://hosting.biz-panel.com/node/465

**Comment by yaroslav-synapse** [comment]
Ссылки на мобильных поправлены - https://github.com/synapse-studio/adaptive/commit/98b1cbdd2ff385d2fca376a8c597d8b4fc76e34f

Второй уровень меню теперь рабочий.
